/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javasenac;

import javax.swing.JOptionPane;

/**
 *
 * @author Robert51816586
 */
public class Raquete extends javax.swing.JFrame {

    int bat = 0;

    /**
     * Creates new form Raquete
     */
    public Raquete() {
        initComponents();

        carregar.setEnabled(false);
        ligar.setEnabled(false);
        usar.setEnabled(false);
        result.setEnabled(false);

        carregar.setText(bat + " % Bateria");
        usar.setText(bat + " % Bateria");
        ligar.setText("Desligado");

        atualizarResult();
        resetarResult();

    }

    public void atualizarResult() {
        result.setText("Bateria :" + carregar.getText()
                + "\n" + "Usar: " + usar.getText()
                + "\n" + "Ligar: " + ligar.getText());
    }

    public void resetarResult() {
        carregar.setText(bat + " % Bateria");
        usar.setText(bat + " % Bateria");
        ligar.setText("Desligado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarregar = new javax.swing.JButton();
        btnUsar = new javax.swing.JButton();
        btnLigar = new javax.swing.JButton();
        carregar = new javax.swing.JTextField();
        usar = new javax.swing.JTextField();
        ligar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarregar.setText("Carregar");
        btnCarregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarregarMouseClicked(evt);
            }
        });

        btnUsar.setText("Usar");
        btnUsar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsarMouseClicked(evt);
            }
        });

        btnLigar.setText("Ligar");
        btnLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLigarMouseClicked(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLigar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(usar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ligar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregar)
                    .addComponent(carregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUsar)
                            .addComponent(usar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLigar)
                    .addComponent(ligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarregarMouseClicked
        bat = bat + 100;
        btnCarregar.getText();

        if (bat > 100) {
            JOptionPane.showMessageDialog(null, "Bateria carregada");
            bat = 100;
            carregar.setText(bat + "% Bateria");
            usar.setText(bat + "% Bateria");
        }
        carregar.setText(bat + "% Bateria");
        usar.setText(bat + "% Bateria");
        atualizarResult();
    }//GEN-LAST:event_btnCarregarMouseClicked

    private void btnLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigarMouseClicked
        if (bat == 100) {
            btnLigar.getText();
            ligar.setText("Raquete ligada");
        } else {
            JOptionPane.showMessageDialog(null, "Carregue bateria 100% para ligar");
        }
        atualizarResult();
    }//GEN-LAST:event_btnLigarMouseClicked

    private void btnUsarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsarMouseClicked
        if (bat > 00 && ligar.getText().equals("Raquete ligada")) {
            bat = bat - 10;
            btnUsar.getText();
            usar.setText(bat + "% Bateria");
            carregar.setText(bat + "% Bateria");
            atualizarResult();
            if (bat == 0) {
                JOptionPane.showMessageDialog(null, "Bateria Maquina Desligada");
                resetarResult();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bateria Maquina Desligada");

        }

    }//GEN-LAST:event_btnUsarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Raquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnUsar;
    private javax.swing.JTextField carregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ligar;
    private javax.swing.JTextArea result;
    private javax.swing.JTextField usar;
    // End of variables declaration//GEN-END:variables
}
