/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javasenac;

import javax.swing.JOptionPane;

/**
 *
 * @author robert51816586
 */
public class Aeronave extends javax.swing.JFrame {
int acumulador = 0;
    /**
     * Creates new form Aeronave
     */
    public Aeronave() {
        initComponents();
        
        stsLigado.setEnabled(false);
        checklist.setEnabled(false);
        autorizarDecolagem.setEnabled(false);
        subir.setEnabled(false);
        autorizarDescer.setEnabled(false);
        descer.setEnabled(false);
        desligar.setEnabled(false);
        
        
        stsLigado.setText("Desligado");
        checklist.setText("Não feito");
        autorizarDecolagem.setText("Não autorizado");
        subir.setText(acumulador+"0 mil pes");
        autorizarDescer.setText("Não autorizado");
        descer.setText(acumulador+"Não autorizado");
        desligar.setText("Desligado");
       
        
        result.setEnabled(false);
       
        atualizarResult();
    }
public void atualizarResult(){
     result.setText("Ligado : "+ stsLigado.getText()+" \n"+"checklist : "+checklist.getText()+"\n"+"Autorizar: "+autorizarDecolagem.getText()+
                "\n"+"Subir :" +subir.getText()+"\n"+ "Autorizar Decida: "+autorizarDecolagem.getText()+ "\n"+ "Descer: "+descer.getText()+"\n"
        +"Desligar: "+desligar.getText()+"\n"+"Resetar :");
}

public void resetarResult(){
    stsLigado.setText("Desligado");
        checklist.setText("Não feito");
        autorizarDecolagem.setText("Não autorizado");
        subir.setText(acumulador+"0 mil pes");
        autorizarDescer.setText("Não autorizado");
        descer.setText(acumulador+"0 mil pes");
        desligar.setText("Desligado");
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLigar = new javax.swing.JButton();
        btnAutorizarDecolar = new javax.swing.JButton();
        btnCheckList = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnAutorizarDescer = new javax.swing.JButton();
        btnDescer = new javax.swing.JButton();
        btnDesligar = new javax.swing.JButton();
        stsLigado = new javax.swing.JTextField();
        checklist = new javax.swing.JTextField();
        autorizarDecolagem = new javax.swing.JTextField();
        subir = new javax.swing.JTextField();
        autorizarDescer = new javax.swing.JTextField();
        descer = new javax.swing.JTextField();
        desligar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLigar.setText("btnLigar");
        btnLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLigarMouseClicked(evt);
            }
        });
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });

        btnAutorizarDecolar.setText("btnAutorizarDecolar");
        btnAutorizarDecolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutorizarDecolarMouseClicked(evt);
            }
        });

        btnCheckList.setText("btnCheckList");
        btnCheckList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckListMouseClicked(evt);
            }
        });
        btnCheckList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckListActionPerformed(evt);
            }
        });

        btnSubir.setText("btnSubir");
        btnSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubirMouseClicked(evt);
            }
        });

        btnAutorizarDescer.setText("btnAutorizarDescer");
        btnAutorizarDescer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutorizarDescerMouseClicked(evt);
            }
        });
        btnAutorizarDescer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarDescerActionPerformed(evt);
            }
        });

        btnDescer.setText("btnDescer");
        btnDescer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescerMouseClicked(evt);
            }
        });

        btnDesligar.setText("btnDesligar");
        btnDesligar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesligarMouseClicked(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAutorizarDecolar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCheckList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLigar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checklist, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stsLigado, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(autorizarDecolagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAutorizarDescer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnSubir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subir, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(autorizarDescer))
                        .addGap(450, 450, 450))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDesligar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnDescer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desligar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(449, 449, 449))))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLigar)
                    .addComponent(stsLigado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckList)
                    .addComponent(checklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutorizarDecolar)
                    .addComponent(autorizarDecolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubir)
                    .addComponent(subir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutorizarDescer)
                    .addComponent(autorizarDescer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescer)
                    .addComponent(descer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesligar))
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(822, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLigarActionPerformed

    private void btnLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigarMouseClicked
       btnLigar.getText();
       stsLigado.setText("Avisão Ligado");
       atualizarResult();
    }//GEN-LAST:event_btnLigarMouseClicked

    private void btnCheckListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckListActionPerformed

    private void btnCheckListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckListMouseClicked
        /*btnCheckList.getText();
        checklist.setText("Checklist feito");
        atualizarResult();*/
        if(stsLigado.getText().equals("Desligado")){
            JOptionPane.showMessageDialog(null, "Ligue o avião");  
        }else{
            checklist.setText("Checklist Feito");
            atualizarResult();
        }
    }//GEN-LAST:event_btnCheckListMouseClicked

    private void btnAutorizarDecolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorizarDecolarMouseClicked
        if(checklist.getText().equals("Não feito")){
           JOptionPane.showMessageDialog(null, "Faça o checklist"); 
        }else{
           autorizarDecolagem.setText("Autorizado para decolagem");
           atualizarResult();
        }
    }//GEN-LAST:event_btnAutorizarDecolarMouseClicked

    private void btnSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseClicked
        if(autorizarDecolagem.getText().equals("Não autorizado")){
           JOptionPane.showMessageDialog(null, "Faça o atorização antes"); 
        }else{
           acumulador+=10;
           subir.setText("subiu para: "+acumulador +" mil pes");
           
        }
            atualizarResult();       
    }//GEN-LAST:event_btnSubirMouseClicked

    private void btnAutorizarDescerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorizarDescerMouseClicked
        
        if(acumulador> 0){
           autorizarDescer.setText("Decida autorizada");
           atualizarResult();
        }else{
            JOptionPane.showMessageDialog(null, "Decida não autorizada");
        }
    }//GEN-LAST:event_btnAutorizarDescerMouseClicked

    private void btnDescerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescerMouseClicked
        if(autorizarDescer.getText().equals("Decida autorizada")&&acumulador>0){ 
           acumulador-=10;
           subir.setText("subiu para: "+acumulador +" mil pes");
           descer.setText("subiu para: "+acumulador +" mil pes")
           ;
           if(acumulador <=0){
            JOptionPane.showMessageDialog(null, "Aviao no chão");
        }
        }else{
           JOptionPane.showMessageDialog(null, "Faça o atorização antes"); 
        }
        
            atualizarResult();   
           
    }//GEN-LAST:event_btnDescerMouseClicked

    private void btnDesligarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesligarMouseClicked
     if(acumulador ==0){
         resetarResult();
     }else{
         JOptionPane.showMessageDialog(null, "Aviao no alto");
     }
    }//GEN-LAST:event_btnDesligarMouseClicked

    private void btnAutorizarDescerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarDescerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutorizarDescerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aeronave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorizarDecolagem;
    private javax.swing.JTextField autorizarDescer;
    private javax.swing.JButton btnAutorizarDecolar;
    private javax.swing.JButton btnAutorizarDescer;
    private javax.swing.JButton btnCheckList;
    private javax.swing.JButton btnDescer;
    private javax.swing.JButton btnDesligar;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JTextField checklist;
    private javax.swing.JTextField descer;
    private javax.swing.JTextField desligar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea result;
    private javax.swing.JTextField stsLigado;
    private javax.swing.JTextField subir;
    // End of variables declaration//GEN-END:variables
}
